name: Autograding Tests
'on':
    schedule:
      - cron: '0 0 31 3 *'
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: 'github.actor != ''github-classroom[bot]'''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        run: ./mp2.sh pull

      - name: Decrypt Private Tests
        run: >
          openssl enc -aes-256-cbc -d -in test/private_tests.zip.enc -out
          test/private.zip -k ${{ secrets.DECRYPT_PASSWORD }} -pbkdf2

      - name: Unzip Private Tests
        run: cd test && unzip private.zip

      - name: Run all the tests
        id: test-all
        run: scripts/action_grader.sh
        shell: bash
