name: Scheduled Submit Workflow
'on':
    schedule:
      - cron: '0 0 10 4 *'
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: 'github.actor != ''github-classroom[bot]'''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        run: ./mp2.sh pull

      - name: Decrypt Private Tests
        run: >
          openssl enc -aes-256-cbc -d -in test/private_tests.zip.enc -out
          test/private.zip -k ${{ secrets.DECRYPT_PASSWORD }} -pbkdf2

      - name: Unzip Private Tests
        run: cd test && unzip private.zip

      - name: Run all the tests
        id: test-all
        run: |
          scripts/action_grader.sh

          SCORE=$(cat score.txt)
          STUDENT_ID=$(cat ./student_id.txt)
          echo "SCORE=$SCORE" >> $GITHUB_ENV
          echo "STUDENT_ID=$STUDENT_ID" >> $GITHUB_ENV
        shell: bash

      - name: Submit grade to TA's repo
        run: |
          git config --global user.name "Student Bot"
          git config --global user.email "student@github.com"

          git clone "https://$GITHUB_ACTOR:${{ secrets.TA_REPO_TOKEN }}@github.com/${{ secrets.TA_REPO }}.git" grades_repo
          cd grades_repo

          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "$STUDENT_ID,$SCORE,$TIMESTAMP" | tee -a $STUDENT_ID.txt

          git add $STUDENT_ID.txt
          git commit -m "Update grade for $STUDENT_ID"
          git push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TA_REPO: ${{ secrets.TA_REPO }}
          TA_REPO_TOKEN: ${{ secrets.TA_REPO_TOKEN }}
